export const ActionTypes = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECT_PRODUCT : "SELECT_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT" 
}